allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher@2.5.6'
  - '@swc/core@1.15.40'
  - sharp@0.34.5
  - unrs-resolver@1.12.2
